### ISSUE TITLE
Addition of classes in Class Library

### ISSUE THREAD

**Issue by CiaraM100104** [GothicLolita229/CSC-253-Mortuus#1]
Creating classes for potions, treasures, rooms, weapons, players, items, mobs as well as game systems. Using inheritance to make the creation go much smoother.

- [x] InGameItem Class
- [x] Create Item: InGameItem Class
- [x] ReadFile and add file to list, ReadCSVFile Class 
- [x] Mover Class
- [x] Options Menu Class
- [x] Mob Class: Living Thing Class
- [x] Mover Class
- [x] Player Class: Living Thing Class
- [x] Potion Class: InGameItem Class
- [x] Room Class
- [x] Treasure Class: InGameItem Class
- [x] Weapon Class: InGameItem Class

**Comment by CiaraM100104** [comment]
Main classes were all added, I created all of the classes besides Moverclass and Loadplayer class. I only filled out the Rooms, Weapons, Items and Readfile. Lourdes filled out the other minor classes along with adding inheritance and created the Loadplayer and moverclass.

**Comment by GothicLolita229** [comment]
We also added an options menu class and reconfigured much of the code with how to navigate the systems and get information
